#!/bin/bash

usage() {
    echo "Usage: ./cvm-cli <command> [options]"
    echo ""
    echo "Commands:"
    echo "  deploy-azure        Deploy a VM onto Azure using azure_disk.vhd."
    echo "  deploy-aws          Deploy a VM onto AWS using aws_disk.vmdk."
    echo "  deploy-gcp          Deploy a VM onto GCP using gcp_disk.tar.gz."
    echo "  update-workload     Update the workload on a deployed CVM."
    echo "  update-disk         Update the workload on a specified disk file."
    echo "  sign-image          Sign and verify a container image using Cosign."
    echo ""
    echo "Arguments for 'deploy-azure' command:"
    echo "  --resource_group <group>    The resource group for the deployment. **Mandatory**"
    echo "  --storage_account <name>    The name of a custom storage account. Must be in the resource group you list. **Mandatory**"
    echo "  --gallery_name <name>       The name of a shared image gallery. Must be in the resource group you list. **Mandatory**"
    echo "  --additional_ports <ports>  Comma-separated list of additional ports to open (e.g., \"80,443\"). Default: None"
    echo "  --vm_name <name>            The name of the virtual machine. Default: cvm_test"
    echo "  --vm_type <type>            The type of VM to be deployed. Default: \"Standard_DC2es_v5\""
    echo ""
    echo "Arguments for 'deploy-gcp' command:"
    echo "  --project_id <id>           The project id for the deployment. **Mandatory**"
    echo "  --bucket <name>             The name of a gcp bucket to store the vm image to. **Mandatory**"
    echo "  --additional_ports <ports>  Comma-separated list of additional ports to open (e.g., \"80,443\"). Default: None"
    echo "  --vm_name <name>            The name of the virtual machine. Default: cvm-test"
    echo "  --region <region>           The region where the VM will be deployed. Default: \"asia-southeast1-b\""
    echo "  --vm_type <type>            The type of VM to be deployed. Default: \"c3-standard-4\""
    echo ""
    echo "Arguments for 'deploy-aws' command:"
    echo "  --bucket <name>             The name of an AWS bucket to store the vm image to. **Mandatory**"
    echo "  --additional_ports <ports>  Comma-separated list of additional ports to open (e.g., \"80,443\"). Default: None"
    echo "  --vm_name <name>            The name of the virtual machine. Default: cvm-test"
    echo "  --region <region>           The region where the VM will be deployed. Default: \"us-east-2\""
    echo "  --vm_type <type>            The type of VM to be deployed. Default: \"m6a.large\""
    echo ""
    echo "Additional arguments for the 'update-workload' command:"
    echo "  <VM IP>                 The IP of the VM running on the CSP."
    echo "  <API TOKEN>             API token authorize the workload change."
    echo ""
    echo "Additional arguments for the 'update-disk' command:"
    echo "  <DISK PATH>             The path to your disk image."
    echo ""
    echo "Arguments for 'sign-image' command:"
    echo "  <source-image>           Source image (e.g., alpine:latest)"
    echo "  <target-image>           Target image (e.g., docker.io/user/image:signed)"
    echo "  <cosign-private>         Cosign private key"
    echo "  <cosign-public>          Cosign public key"
    echo ""
    exit 1
}

COMMAND=$1
shift 1  # Shift to process other arguments

if [[ -z "$COMMAND" ]]; then
    usage
fi

case "$COMMAND" in
    deploy-aws)
        VM_NAME="cvm-test"
        BUCKET=""
        REGION="us-east-2"
        VM_TYPE="m6a.large"
        ADDITIONAL_PORTS=""

        while [[ "$#" -gt 0 ]]; do
            case "$1" in
                --additional_ports)
                    ADDITIONAL_PORTS=$2
                    shift 2
                    ;;
                --vm_name)
                    VM_NAME=$2
                    shift 2
                    ;;
                --region)
                    REGION=$2
                    shift 2
                    ;;
                --vm_type)
                    VM_TYPE=$2
                    shift 2
                    ;;
                --bucket)
                    BUCKET=$2
                    shift 2
                    ;;
                *)
                    echo "Unknown argument: $1"
                    usage
                    ;;
            esac
        done

        if [[ -z "$BUCKET" ]]; then
            usage
        fi

        set -e
        echo "Deploying aws_disk.vmdk with the following parameters:"
        echo "🔹VM Name: $VM_NAME"
        echo "🔹Region: $REGION"
        echo "🔹VM Type: $VM_TYPE"
        echo "🔹Bucket : $BUCKET"
        echo "🔹Additional Ports: $ADDITIONAL_PORTS"
        ./scripts/make_aws_vm.sh "$VM_NAME" "$REGION" "$VM_TYPE" "$BUCKET" "$ADDITIONAL_PORTS"
        set +e
        ;;

    deploy-gcp)
        # Default values
        PROJECT_ID=""
        BUCKET=""
        VM_NAME="cvm-test"
        REGION="asia-southeast1-b"
        VM_TYPE="c3-standard-4"
        # To specify additional workload ports, pass them as a comma-separated string
        # eg. "80,443"
        ADDITIONAL_PORTS=""

        while [[ "$#" -gt 0 ]]; do
            case "$1" in
                --additional_ports)
                    ADDITIONAL_PORTS=$2
                    shift 2
                    ;;
                --vm_name)
                    VM_NAME=$2
                    shift 2
                    ;;
                --region)
                    REGION=$2
                    shift 2
                    ;;
                --project_id)
                    PROJECT_ID=$2
                    shift 2
                    ;;
                --vm_type)
                    VM_TYPE=$2
                    shift 2
                    ;;
                --bucket)
                    BUCKET=$2
                    shift 2
                    ;;
                *)
                    echo "Unknown argument: $1"
                    usage
                    ;;
            esac
        done

        if [[ -z "$PROJECT_ID" || -z "$BUCKET" ]]; then
            usage
        fi

        set -e
        echo "Deploying gcp_disk.tar.gz with the following parameters:"
        echo "🔹VM Name: $VM_NAME"
        echo "🔹Region: $REGION"
        echo "🔹Project ID: $PROJECT_ID"
        echo "🔹VM Type: $VM_TYPE"
        echo "🔹Bucket : $BUCKET"
        echo "🔹Additional Ports: $ADDITIONAL_PORTS"
        ./scripts/make_gcp_vm.sh "$VM_NAME" "$REGION" "$PROJECT_ID" "$VM_TYPE" "$BUCKET" "$ADDITIONAL_PORTS"
        set +e
        ;;

    deploy-azure)
        # Default values
        VM_NAME="cvm_test"
        RESOURCE_GROUP=""
        VM_TYPE="Standard_DC2es_v5"
        # To specify additional workload ports, pass them as a comma-separated string
        # eg. "80,443"
        ADDITIONAL_PORTS=""
        STORAGE_ACC=""
        GALLERY_NAME=""

        while [[ "$#" -gt 0 ]]; do
            case "$1" in
                --additional_ports)
                    ADDITIONAL_PORTS=$2
                    shift 2
                    ;;
                --vm_name)
                    VM_NAME=$2
                    shift 2
                    ;;
                --resource_group)
                    RESOURCE_GROUP=$2
                    shift 2
                    ;;
                --vm_type)
                    VM_TYPE=$2
                    shift 2
                    ;;
                --storage_account)
                    STORAGE_ACC=$2
                    shift 2
                    ;;
                --gallery_name)
                    GALLERY_NAME=$2
                    shift 2
                    ;;
                *)
                    echo "Unknown argument: $1"
                    usage
                    ;;
            esac
        done

        if [[ -z "$RESOURCE_GROUP" || -z "$STORAGE_ACC" || -z "$GALLERY_NAME" ]]; then
            usage
        fi

        set -e
        echo "Deploying azure_disk.vhd with the following parameters:"
        echo "🔹VM Name: $VM_NAME"
        echo "🔹Resource Group: $RESOURCE_GROUP"
        echo "🔹VM Type: $VM_TYPE"
        echo "🔹Additional Ports: $ADDITIONAL_PORTS"
        echo "🔹Storage Account: $STORAGE_ACC"
        echo "🔹Shared Image Gallery: $GALLERY_NAME"
        ./scripts/make_azure_vm.sh "$VM_NAME" "$RESOURCE_GROUP" "$VM_TYPE" "$ADDITIONAL_PORTS" "$STORAGE_ACC" "$GALLERY_NAME"
        set +e
        ;;

    update-disk)
        DISK_FILE=$1
        shift 1
        if [[ -z "$DISK_FILE" ]]; then
            echo "❌ Please provide the disk file (e.g., azure_disk.vhd)"
            exit 1
        fi
        os_type="$(uname)"
        if [[ "$os_type" == "Linux" ]]; then
            echo "Reloading workload onto an existing disk..."
            ./scripts/copy_workload_to_existing_disk.sh $DISK_FILE
        elif [[ "$os_type" == "Darwin" ]]; then
            echo "🔁 Using Multipass to update workload..."
            SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/scripts" && pwd)"
            bash "$SCRIPTS_DIR/update_disk_via_multipass.sh" "$DISK_FILE"
        else
            echo "Unsupported OS: $os_type"
            exit 1
        fi
        ;;

    update-workload)
        IP=$1
        PASSWORD=$2
        shift 2
        if [[ -z "$IP" || -z "$PASSWORD" ]]; then
            usage
        fi
        ./scripts/update-remote-workload.sh $IP $PASSWORD
        ;;
    
    sign-image)
        SOURCE_IMAGE="$1"
        TARGET_IMAGE="$2"
        COSIGN_PRI="$3"
        COSIGN_PUB="$4"

        shift 2
        if [[ -z "$SOURCE_IMAGE" || -z "$TARGET_IMAGE" || -z "$COSIGN_PRI" || -z "$COSIGN_PUB" ]]; then
            usage
        fi
        ./scripts/sign-and-verify.sh $SOURCE_IMAGE $TARGET_IMAGE $COSIGN_PRI $COSIGN_PUB
        ;;

    *)
        echo "Unknown command: $COMMAND"
        usage
        ;;
esac

exit 0
