networks:
  monitoring:
    driver: bridge

services:
  node-exporter:
    image: docker.io/prom/node-exporter:v1.9.1
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100/tcp
    networks:
      - monitoring

  vmagent:
    image: docker.io/victoriametrics/vmagent:v1.108.1
    container_name: vmagent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./secrets/vmagent.yml:/etc/vmagent/vmagent.yml:ro
      - ./secrets/vmagent-entrypoint.sh:/entrypoint.sh:ro
      - ./secrets/discover-identity.sh:/etc/discover-identity.sh:ro
      - ./secrets/identity.env:/etc/identity.env:ro
      - /data/data-disk:/data/data-disk
      - /data/data-disk/vmagent:/vmagentdata
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    command:
      - "-remoteWrite.url=https://${METRICS_HOST}/api/v1/write"
      - "-remoteWrite.basicAuth.username=${METRICS_USER}"
      - "-remoteWrite.basicAuth.password=${METRICS_PASSWORD}"
      - "-remoteWrite.tmpDataPath=/vmagentdata"
      - "-remoteWrite.maxDiskUsagePerURL=128MB"
